//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMasterPAPI.Strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameMasterPAPI.Strings.General_DE", typeof(General_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        /// </summary>
        internal static string dateLabel {
            get {
                return ResourceManager.GetString("dateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Design ähnelt.
        /// </summary>
        internal static string designLabel {
            get {
                return ResourceManager.GetString("designLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Antik ähnelt.
        /// </summary>
        internal static string designMedieval {
            get {
                return ResourceManager.GetString("designMedieval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modern ähnelt.
        /// </summary>
        internal static string designModern {
            get {
                return ResourceManager.GetString("designModern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magische Moderne ähnelt.
        /// </summary>
        internal static string genre_magicalWorld {
            get {
                return ResourceManager.GetString("genre_magicalWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mittelalter Fantasy ähnelt.
        /// </summary>
        internal static string genre_medievalFantasy {
            get {
                return ResourceManager.GetString("genre_medievalFantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nuklearer Fallout ähnelt.
        /// </summary>
        internal static string genre_nuclearFallout {
            get {
                return ResourceManager.GetString("genre_nuclearFallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Space Opera ähnelt.
        /// </summary>
        internal static string genre_spaceOpera {
            get {
                return ResourceManager.GetString("genre_spaceOpera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Genre ähnelt.
        /// </summary>
        internal static string genreLabel {
            get {
                return ResourceManager.GetString("genreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game Master Name ähnelt.
        /// </summary>
        internal static string gmNameLabel {
            get {
                return ResourceManager.GetString("gmNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
        /// </summary>
        internal static string languageEnglish {
            get {
                return ResourceManager.GetString("languageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        internal static string languageGerman {
            get {
                return ResourceManager.GetString("languageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string languageLabel {
            get {
                return ResourceManager.GetString("languageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Spiel ähnelt.
        /// </summary>
        internal static string newGameButton {
            get {
                return ResourceManager.GetString("newGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optionen ähnelt.
        /// </summary>
        internal static string optionsButton {
            get {
                return ResourceManager.GetString("optionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        internal static string quitButton {
            get {
                return ResourceManager.GetString("quitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurück ähnelt.
        /// </summary>
        internal static string returnButton {
            get {
                return ResourceManager.GetString("returnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gespeicherte Spiele ähnelt.
        /// </summary>
        internal static string savedGamesLabel {
            get {
                return ResourceManager.GetString("savedGamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansehen ähnelt.
        /// </summary>
        internal static string showButton {
            get {
                return ResourceManager.GetString("showButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starten ähnelt.
        /// </summary>
        internal static string startButton {
            get {
                return ResourceManager.GetString("startButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen ähnelt.
        /// </summary>
        internal static string welcomeLabel {
            get {
                return ResourceManager.GetString("welcomeLabel", resourceCulture);
            }
        }
    }
}
